name: Linting

on:
  push:
    paths:
      - "**.[jt]s"
      - ".eslint*"
      - ".prettier*"
      - ".github/workflows/linting.yaml"

  pull_request:
    paths:
      - "**.[jt]s"
      - ".eslint*"
      - ".prettier*"
      - ".github/workflows/linting.yaml"

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn run lint:ci
