name: Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

    paths-ignore:
      - ".*/**"
      - "!.github/workflows/pull_request.yaml"
      - "vscode/**"
      - ".env.example"
      - "LICENSE"
      - "*.md"

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Lint Pull Request Title
        uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn run lint:ci

      - name: Test
        run: yarn test --ci --colors --collectCoverage
