name: Push

on:
  push:
    branches-ignore:
      # master is covered under the release workflow
      - master
    paths-ignore:
      - ".*/**"
      - "!.github/workflows/push.yaml"
      - "vscode/**"
      - ".env.example"
      - "LICENSE"
      - "*.md"

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --ci --colors --frozen-lockfile

      - name: Lint
        run: yarn run lint:ci

      - name: Test
        run: yarn test --ci --colors --collectCoverage
