name: Release

on:
  push:
    branches:
      - master

jobs:
  jest:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: yarn release --ci --colors
