name: Release

on:
  push:
    branches:
      - master

    paths-ignore:
      - ".*/**"
      - "!.github/workflows/release.yaml"
      - "CHANGELOG.md"
      - "package.json"

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn run lint:ci

      - name: Test
        run: yarn test --ci --colors --collectCoverage

      - name: Semantic Release
        run: yarn release --ci --colors
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
