name: Testing

on:
  push:
    paths:
      - "**.[jt]s"
      - "package.json"
      - "yarn.lock"
      - "tsconfig.json"
      - ".github/workflows/testing.yaml"

  pull_request:
    paths:
      - "**.[jt]s"
      - "package.json"
      - "yarn.lock"
      - "tsconfig.json"
      - ".github/workflows/testing.yaml"

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1

      - name: Run tests with coverage
        run: yarn test --ci --colors --collectCoverage
